### ISSUE TITLE
Freezing when clicking statistics

### ISSUE THREAD

**Issue by miranro** [Belieal/flipping-utilities#96] opened 2020-08-07 14:12 UTC
Hello,

Lately whenever I press statistics my gameclient freezes for up to a minute. Is this a known issue, any work arounds?

Thanks in advance.

**Comment by zumaad** [comment] 2020-08-08 18:35
Hi., this is a known issue with a fix that we already know about but unfortunately we haven't been able to release it because i haven't been able to get in contact with Belieal. In the meantime, you can clear your flipping panel. The problem is because of the time java swing takes to clear the sub panels panels when you switch to another panel.

**Comment by zumaad** [comment] 2020-09-17 19:30
this has been fixed with the last release ( a couple of weeks ago I think). @miranro thanks for the description!

**Closed** 2020-09-17 19:31 UTC
